name: quds_interactive
description: An easy localization (with customizing), with dynamic theme!
version: 0.0.4+5
homepage: https://www.alrazysoft.com
repository: https://github.com/MohammedAsaadAsaad/quds_interactive

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quds_ui_kit: ^0.0.7+2
  quds_provider: ^0.0.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/flags/ 